#!/bin/bash
yum update -y
yum install httpd -y
service httpd start
chkconfig httpd on
aws s3 cp s3://bcp.ec2.site/index.html /var/www/html/
curl http://169.254.169.254/latest/meta-data/instance-type > /var/www/html/type.html
